app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

  database-access-type: jpa

  retry-policy:
    policy: constant
    max-attempts: 3
    backoff-initial-delay: 1s
    backoff-appender: 2

  use-queue: true


spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
