app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

  database-access-type: jpa

  retry-policy:
    retry-type: constant
    max-attempts: 3
    backoff-initial-delay: 1s
    backoff-appender: 2

  topic:
    name: bot_updates
    partitions: 5
    replicas: 2

  use-queue: false



spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5437/scrapper
    username: postgres
    password: postgres

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      base-path: ''
      exposure:
        include: '*'
      path-mapping:
        prometheus: 'metrics'
  metrics:
    tags:
      application: '${spring.application.name}'
  health:
    probes:
      enabled: true
  info:
    git:
      mode: 'full'
  server:
    port: 8081 # отдельный порт для management endpoint'ов
micrometer:
  registry:
    prometheus:
      enabled: true
      step: PT1M
